USE `ROOM-MANAGEMENT-WEB`;

ALTER TABLE MAINTENANCE_REQUEST
DROP COLUMN SERVICE_ROOM_ID;

ALTER TABLE SERVICE
ADD COLUMN SERVICE_TYPE VARCHAR(40);

ALTER TABLE ROOM
    ADD COLUMN PRICE decimal(10,2);

ALTER TABLE SERVICE
    ADD COLUMN PRICE decimal(10,2);

ALTER TABLE SERVICE_ROOM
DROP COLUMN SERVICE_TYPE;

ALTER TABLE SERVICE_ROOM
DROP COLUMN IS_ACTIVE;

ALTER TABLE ROOM_MEMBER
DROP COLUMN ROOM_ID, DROP COLUMN IS_ROOM_REPRESENTATIVE;


-- update sql 20/4
ALTER TABLE invoice
    MODIFY PAYMENT_ID INT;
ALTER TABLE invoice
DROP COLUMN PHONE_NUMBER, DROP COLUMN CCCD,DROP COLUMN EMAIL ;
ALTER TABLE INVOICE
    ADD COLUMN YEAR_CALCULATE INT, ADD COLUMN MONTH_CALCULATE INT;
--------
