USE `ROOM-MANAGEMENT-WEB`;
ALTER TABLE CONTRACT
    ADD COLUMN TRANSACTION_ID VARCHAR(100);

ALTER TABLE USER
    ADD COLUMN TRANSACTION_ID VARCHAR(100);

ALTER TABLE CONTRACT
    MODIFY COLUMN START_DATE TIMESTAMP,
    MODIFY COLUMN END_DATE TIMESTAMP;


ALTER TABLE INVOICE
DROP COLUMN INVOICE_DETAIL_ID;

DROP TABLE INVOICE_DETAIL;

ALTER TABLE INVOICE
    MODIFY COLUMN DUE_DATE TIMESTAMP,
    MODIFY COLUMN PAYMENT_DATE TIMESTAMP;

ALTER TABLE ROOM
    ADD COLUMN NAME NVARCHAR(100);

ALTER TABLE USER
    ADD COLUMN STATUS NVARCHAR(20);