services:
  mysql-room-management-web:
    image: mysql:8.0.33
    container_name: mysql-room-management-web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "room-management-web"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./personal_project_back-end/common-service/src/main/resources/sqls/sql_final_2.sql:/docker-entrypoint-initdb.d/init.sql
    command: --lower_case_table_names=1 --innodb_use_native_aio=0 --innodb_doublewrite=0 --innodb_flush_method=nosync --innodb_buffer_pool_size=128M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456789"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  auth-service:
    build:
      context: ./personal_project_back-end
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "9996:9996"
    environment:
      - SPRING_PROFILES_ACTIVE=thanhdat
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - APP_SERVICE_FILE_URL=http://file-service:9994
      - APP_SERVICE_PAYMENT_URL=http://payment-service:9995
      - APP_SERVICE_AUTH_URL=http://auth-service:9996
      - APP_SERVICE_MAIN_URL=http://main-service:9997
      - APP_SERVICE_NOTIFY_URL=http://notify-service:9998
    depends_on:
      mysql-room-management-web:
        condition: service_healthy

  main-service:
    build:
      context: ./personal_project_back-end
      dockerfile: main-service/Dockerfile
    container_name: main-service
    ports:
      - "9997:9997"
    environment:
      - SPRING_PROFILES_ACTIVE=thanhdat
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - APP_SERVICE_FILE_URL=http://file-service:9994
      - APP_SERVICE_PAYMENT_URL=http://payment-service:9995
      - APP_SERVICE_AUTH_URL=http://auth-service:9996
      - APP_SERVICE_MAIN_URL=http://main-service:9997
      - APP_SERVICE_NOTIFY_URL=http://notify-service:9998
    depends_on:
      mysql-room-management-web:
        condition: service_healthy

volumes:
  mysql_data:

